name: Documentation

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          args: --verbose

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Update manual to ${{ github.ref }}
          body: |
            ${{ steps.git-cliff.outputs.changelog }}
          draft: false
          prerelease: false
